mode: "random"
device: "cpu" # choose device from cuda,cpu

increase:
  step_increment: 64
  start_size: 256
  max_size: 2048


random:
  max_dim_size: 512
  min_dim_size: 1
  max_dim_num: 4
  min_dim_num: 1

