mode: "increase"

increase:
  max_dim_size: 512
  min_dim_size: 1
  step_increment: 64
  dim_num: 3
  tensor_num: 4

random:
  max_tensor_num: 8
  min_tensor_num: 2
  max_tensor_dim: 4
  min_tensor_dim: 1
  max_dim_size: 512
  min_dim_size: 256
