mode: "increase"

random:
  min_boxes: 10
  max_boxes: 1000
  min_iou_threshold: 0.3
  max_iou_threshold: 0.7

increase:
  start_num_boxes: 50
  step_increment: 50
  max_boxes: 1000
  base_iou_threshold: 0.3
  iou_increment: 0.05
