mode: "increase"

increase:
  MAX_DIM_NUM: 20
  SINGLE_DIM_LENGTH_MAX: 4096
  SINGLE_DIM_LENGTH_MIN: 1
  MIN_DIM_NUM: 1
  BASIC_NUMBER: 16
random:
  MAX_DIM_NUM: 10
  SINGLE_DIM_LENGTH_MAX: 512
  SINGLE_DIM_LENGTH_MIN: 1
  MIN_DIM_NUM: 1