mode: "random"

increase:
  step_increment: 256
  start_sparsity: 0.01
  sparsity_max: 0.5
  sparsity_increment: 0.01
  m: 512
  n: 512
  p: 512

random:
  max_sparsity: 0.6
  min_sparsity: 0.01
  max_dim_size: 512
  min_dim_size: 1
